###############################################################################
# Helm values that install Dagster + your user‑code deployment on AKS.
###############################################################################

dagsterApiServer:
  service:
    type: LoadBalancer           # <- makes the gRPC API public (handy for local dev)

dagsterWebserver:
  service:
    type: LoadBalancer           # <- exposes the UI

postgresql:
  enabled: true
  persistence:
    enabled: true
    size: 8Gi

rabbitmq:
  enabled: true
  persistence:
    enabled: true
    size: 8Gi

###############################################################################
# User‑code deployment (your Docker image that contains hydrosat_project)
###############################################################################
dagster-user-deployments:
  enabled: true
  deployments:
    - name: hydrosat-code

      # Image is swapped to your ACR by deploy.sh – these are just defaults
      image:
        repository: hydro0ba375acr.azurecr.io/hydrosat
        tag: latest
        pullPolicy: Always

      # Tell Dagster to load definitions from the Python *module*
      dagsterApiGrpcArgs:
        - "-m"
        - "hydrosat_project"
      port: 4000
      workingDirectory: "/app"

      # Environment variables passed into the container
      env:
        # full connection‑string – required by BlobServiceClient
        - name: AZURE_STORAGE_CONNECTION_STRING
          value: "DefaultEndpointsProtocol=https;AccountName=STORAGE_ACCOUNT_NAME;AccountKey=PLACEHOLDER;EndpointSuffix=core.windows.net"

        # account key – required by the IO‑manager
        - name: AZURE_STORAGE_KEY
          value: "PLACEHOLDER"
