# helm/dagster-values.yaml

# Expose Dagster services
dagsterApiServer:
  service:
    type: LoadBalancer

dagsterWebserver:
  service:
    type: LoadBalancer

postgresql:
  enabled: true
  persistence:
    enabled: true
    size: 8Gi

rabbitmq:
  enabled: true
  persistence:
    enabled: true
    size: 8Gi

# Override user code deployments
dagster-user-deployments:
  enabled: true
  deployments:
    - name: hydrosat-code
      image:
        repository: hydro0ba375acr.azurecr.io/hydrosat
        tag: latest
        pullPolicy: Always
      dagsterApiGrpcArgs:
        - "-m"  # Use module loading
        - "hydrosat_project"
      port: 4000
      env:
        - name: AZURE_STORAGE_CONNECTION_STRING
          value: "DefaultEndpointsProtocol=https;AccountName=STORAGE_ACCOUNT_NAME;AccountKey=YOUR_ACCOUNT_KEY;EndpointSuffix=core.windows.net"
      workingDirectory: "/app"

      

